export const languageToCountryMapping = {
  GE: {
    ab: {
      languageCode: "ab",
      languageName: "Abkhazian",
    },
    ka: {
      languageCode: "ka",
      languageName: "Georgian",
    },
    os: {
      languageCode: "os",
      languageName: "Ossetian",
    },
  },
  DJ: {
    aa: {
      languageCode: "aa",
      languageName: "Afar",
    },
  },
  ZA: {
    af: {
      languageCode: "af",
      languageName: "Afrikaans",
    },
    nr: {
      languageCode: "nr",
      languageName: "Southern Ndebele",
    },
    ts: {
      languageCode: "ts",
      languageName: "Tsonga",
    },
    ve: {
      languageCode: "ve",
      languageName: "Venda",
    },
    xh: {
      languageCode: "xh",
      languageName: "Xhosa",
    },
    zu: {
      languageCode: "zu",
      languageName: "Zulu",
    },
  },
  GH: {
    ak: {
      languageCode: "ak",
      languageName: "Akan",
    },
    ee: {
      languageCode: "ee",
      languageName: "Ewe",
    },
    tw: {
      languageCode: "tw",
      languageName: "Twi",
    },
  },
  AL: {
    sq: {
      languageCode: "sq",
      languageName: "Albanian",
    },
  },
  ET: {
    am: {
      languageCode: "am",
      languageName: "Amharic",
    },
    om: {
      languageCode: "om",
      languageName: "Oromo (Afaan Oromo)",
    },
  },
  EG: {
    ar: {
      languageCode: "ar",
      languageName: "Arabic",
    },
  },
  ES: {
    an: {
      languageCode: "an",
      languageName: "Aragonese",
    },
    eu: {
      languageCode: "eu",
      languageName: "Basque",
    },
    ca: {
      languageCode: "ca",
      languageName: "Catalan",
    },
    gl: {
      languageCode: "gl",
      languageName: "Galician",
    },
    es: {
      languageCode: "es",
      languageName: "Spanish",
    },
  },
  AM: {
    hy: {
      languageCode: "hy",
      languageName: "Armenian",
    },
  },
  IN: {
    as: {
      languageCode: "as",
      languageName: "Assamese",
    },
    bh: {
      languageCode: "bh",
      languageName: "Bihari",
    },
    gu: {
      languageCode: "gu",
      languageName: "Gujarati",
    },
    hi: {
      languageCode: "hi",
      languageName: "Hindi",
    },
    kn: {
      languageCode: "kn",
      languageName: "Kannada",
    },
    ks: {
      languageCode: "ks",
      languageName: "Kashmiri",
    },
    ml: {
      languageCode: "ml",
      languageName: "Malayalam",
    },
    mr: {
      languageCode: "mr",
      languageName: "Marathi",
    },
    or: {
      languageCode: "or",
      languageName: "Oriya",
    },
    pi: {
      languageCode: "pi",
      languageName: "Pāli",
    },
    pa: {
      languageCode: "pa",
      languageName: "Punjabi (Eastern)",
    },
    sa: {
      languageCode: "sa",
      languageName: "Sanskrit",
    },
    ta: {
      languageCode: "ta",
      languageName: "Tamil",
    },
    te: {
      languageCode: "te",
      languageName: "Telugu",
    },
  },
  RU: {
    av: {
      languageCode: "av",
      languageName: "Avaric",
    },
    ba: {
      languageCode: "ba",
      languageName: "Bashkir",
    },
    ce: {
      languageCode: "ce",
      languageName: "Chechen",
    },
    cv: {
      languageCode: "cv",
      languageName: "Chuvash",
    },
    kv: {
      languageCode: "kv",
      languageName: "Komi",
    },
    cu: {
      languageCode: "cu",
      languageName: "Old Church Slavonic, Old Bulgarian",
    },
    ru: {
      languageCode: "ru",
      languageName: "Russian",
    },
    tt: {
      languageCode: "tt",
      languageName: "Tatar",
    },
  },
  IR: {
    ae: {
      languageCode: "ae",
      languageName: "Avestan",
    },
    fa: {
      languageCode: "fa",
      languageName: "Persian (Farsi)",
    },
  },
  BO: {
    ay: {
      languageCode: "ay",
      languageName: "Aymara",
    },
  },
  AZ: {
    az: {
      languageCode: "az",
      languageName: "Azerbaijani",
    },
  },
  ML: {
    bm: {
      languageCode: "bm",
      languageName: "Bambara",
    },
  },
  BY: {
    be: {
      languageCode: "be",
      languageName: "Belarusian",
    },
  },
  BD: {
    bn: {
      languageCode: "bn",
      languageName: "Bengali (Bangla)",
    },
  },
  VU: {
    bi: {
      languageCode: "bi",
      languageName: "Bislama",
    },
  },
  BA: {
    bs: {
      languageCode: "bs",
      languageName: "Bosnian",
    },
  },
  FR: {
    br: {
      languageCode: "br",
      languageName: "Breton",
    },
    co: {
      languageCode: "co",
      languageName: "Corsican",
    },
    fr: {
      languageCode: "fr",
      languageName: "French",
    },
    oc: {
      languageCode: "oc",
      languageName: "Occitan",
    },
  },
  BG: {
    bg: {
      languageCode: "bg",
      languageName: "Bulgarian",
    },
  },
  MM: {
    my: {
      languageCode: "my",
      languageName: "Burmese",
    },
  },
  GU: {
    ch: {
      languageCode: "ch",
      languageName: "Chamorro",
    },
  },
  MW: {
    ny: {
      languageCode: "ny",
      languageName: "Chichewa, Chewa, Nyanja",
    },
  },
  CN: {
    zh: {
      languageCode: "zh",
      languageName: "Chinese",
    },
    ii: {
      languageCode: "ii",
      languageName: "Nuosu",
    },
    bo: {
      languageCode: "bo",
      languageName: "Tibetan",
    },
    ug: {
      languageCode: "ug",
      languageName: "Uyghur",
    },
    za: {
      languageCode: "za",
      languageName: "Zhuang, Chuang",
    },
  },
  GB: {
    kw: {
      languageCode: "kw",
      languageName: "Cornish",
    },
    gd: {
      languageCode: "gd",
      languageName: "Gaelic (Scottish)",
    },
    cy: {
      languageCode: "cy",
      languageName: "Welsh",
    },
  },
  CA: {
    cr: {
      languageCode: "cr",
      languageName: "Cree",
    },
    iu: {
      languageCode: "iu",
      languageName: "Inuktitut",
    },
    oj: {
      languageCode: "oj",
      languageName: "Ojibwe",
    },
  },
  HR: {
    hr: {
      languageCode: "hr",
      languageName: "Croatian",
    },
  },
  CZ: {
    cs: {
      languageCode: "cs",
      languageName: "Czech",
    },
  },
  DK: {
    da: {
      languageCode: "da",
      languageName: "Danish",
    },
  },
  MV: {
    dv: {
      languageCode: "dv",
      languageName: "Divehi, Dhivehi, Maldivian",
    },
  },
  NL: {
    nl: {
      languageCode: "nl",
      languageName: "Dutch",
    },
    li: {
      languageCode: "li",
      languageName: "Limburgish (Limburger)",
    },
    fy: {
      languageCode: "fy",
      languageName: "Western Frisian",
    },
  },
  BT: {
    dz: {
      languageCode: "dz",
      languageName: "Dzongkha",
    },
  },
  US: {
    en: {
      languageCode: "en",
      languageName: "English",
    },
    ik: {
      languageCode: "ik",
      languageName: "Inupiak",
    },
    nv: {
      languageCode: "nv",
      languageName: "Navajo",
    },
    yi: {
      languageCode: "yi",
      languageName: "Yiddish",
    },
  },
  "lang-eo": {
    eo: {
      languageCode: "eo",
      languageName: "Esperanto",
    },
  },
  EE: {
    et: {
      languageCode: "et",
      languageName: "Estonian",
    },
  },
  FO: {
    fo: {
      languageCode: "fo",
      languageName: "Faroese",
    },
  },
  FJ: {
    fj: {
      languageCode: "fj",
      languageName: "Fijian",
    },
  },
  FI: {
    fi: {
      languageCode: "fi",
      languageName: "Finnish",
    },
  },
  SN: {
    ff: {
      languageCode: "ff",
      languageName: "Fula, Fulah, Pulaar, Pular",
    },
    wo: {
      languageCode: "wo",
      languageName: "Wolof",
    },
  },
  IM: {
    gv: {
      languageCode: "gv",
      languageName: "Gaelic (Manx)",
    },
  },
  DE: {
    de: {
      languageCode: "de",
      languageName: "German",
    },
  },
  GR: {
    el: {
      languageCode: "el",
      languageName: "Greek",
    },
  },
  GL: {
    kl: {
      languageCode: "kl",
      languageName: "Greenlandic",
    },
  },
  PY: {
    gn: {
      languageCode: "gn",
      languageName: "Guarani",
    },
  },
  HT: {
    ht: {
      languageCode: "ht",
      languageName: "Haitian Creole",
    },
  },
  NG: {
    ha: {
      languageCode: "ha",
      languageName: "Hausa",
    },
    ig: {
      languageCode: "ig",
      languageName: "Igbo",
    },
    yo: {
      languageCode: "yo",
      languageName: "Yoruba",
    },
  },
  IL: {
    he: {
      languageCode: "he",
      languageName: "Hebrew",
    },
  },
  NA: {
    hz: {
      languageCode: "hz",
      languageName: "Herero",
    },
    kj: {
      languageCode: "kj",
      languageName: "Kwanyama",
    },
    ng: {
      languageCode: "ng",
      languageName: "Ndonga",
    },
  },
  PG: {
    ho: {
      languageCode: "ho",
      languageName: "Hiri Motu",
    },
  },
  HU: {
    hu: {
      languageCode: "hu",
      languageName: "Hungarian",
    },
  },
  IS: {
    is: {
      languageCode: "is",
      languageName: "Icelandic",
    },
  },
  "lang-io": {
    io: {
      languageCode: "io",
      languageName: "Ido",
    },
  },
  ID: {
    id: {
      languageCode: "id",
      languageName: "Indonesian",
    },
    jv: {
      languageCode: "jv",
      languageName: "Javanese",
    },
    su: {
      languageCode: "su",
      languageName: "Sundanese",
    },
  },
  "lang-ia": {
    ia: {
      languageCode: "ia",
      languageName: "Interlingua",
    },
  },
  "lang-ie": {
    ie: {
      languageCode: "ie",
      languageName: "Interlingue",
    },
  },
  IE: {
    ga: {
      languageCode: "ga",
      languageName: "Irish",
    },
  },
  IT: {
    it: {
      languageCode: "it",
      languageName: "Italian",
    },
  },
  JP: {
    ja: {
      languageCode: "ja",
      languageName: "Japanese",
    },
  },
  NE: {
    kr: {
      languageCode: "kr",
      languageName: "Kanuri",
    },
  },
  KZ: {
    kk: {
      languageCode: "kk",
      languageName: "Kazakh",
    },
  },
  KH: {
    km: {
      languageCode: "km",
      languageName: "Khmer",
    },
  },
  KE: {
    ki: {
      languageCode: "ki",
      languageName: "Kikuyu",
    },
  },
  RW: {
    rw: {
      languageCode: "rw",
      languageName: "Kinyarwanda (Rwanda)",
    },
  },
  BI: {
    rn: {
      languageCode: "rn",
      languageName: "Kirundi",
    },
  },
  KG: {
    ky: {
      languageCode: "ky",
      languageName: "Kyrgyz",
    },
  },
  CG: {
    kg: {
      languageCode: "kg",
      languageName: "Kongo",
    },
  },
  KR: {
    ko: {
      languageCode: "ko",
      languageName: "Korean",
    },
  },
  TR: {
    ku: {
      languageCode: "ku",
      languageName: "Kurdish",
    },
    tr: {
      languageCode: "tr",
      languageName: "Turkish",
    },
  },
  LA: {
    lo: {
      languageCode: "lo",
      languageName: "Lao",
    },
  },
  VA: {
    la: {
      languageCode: "la",
      languageName: "Latin",
    },
  },
  LV: {
    lv: {
      languageCode: "lv",
      languageName: "Latvian (Lettish)",
    },
  },
  CD: {
    ln: {
      languageCode: "ln",
      languageName: "Lingala",
    },
    lu: {
      languageCode: "lu",
      languageName: "Luga-Katanga",
    },
  },
  LT: {
    lt: {
      languageCode: "lt",
      languageName: "Lithuanian",
    },
  },
  UG: {
    lg: {
      languageCode: "lg",
      languageName: "Luganda, Ganda",
    },
  },
  LU: {
    lb: {
      languageCode: "lb",
      languageName: "Luxembourgish",
    },
  },
  MK: {
    mk: {
      languageCode: "mk",
      languageName: "Macedonian",
    },
  },
  MG: {
    mg: {
      languageCode: "mg",
      languageName: "Malagasy",
    },
  },
  MY: {
    ms: {
      languageCode: "ms",
      languageName: "Malay",
    },
  },
  MT: {
    mt: {
      languageCode: "mt",
      languageName: "Maltese",
    },
  },
  NZ: {
    mi: {
      languageCode: "mi",
      languageName: "Maori",
    },
  },
  MH: {
    mh: {
      languageCode: "mh",
      languageName: "Marshallese",
    },
  },
  MD: {
    mo: {
      languageCode: "mo",
      languageName: "Moldavian",
    },
  },
  MN: {
    mn: {
      languageCode: "mn",
      languageName: "Mongolian",
    },
  },
  NR: {
    na: {
      languageCode: "na",
      languageName: "Nauru",
    },
  },
  ZW: {
    nd: {
      languageCode: "nd",
      languageName: "Northern Ndebele",
    },
    sn: {
      languageCode: "sn",
      languageName: "Shona",
    },
  },
  NP: {
    ne: {
      languageCode: "ne",
      languageName: "Nepali",
    },
  },
  NO: {
    no: {
      languageCode: "no",
      languageName: "Norwegian",
    },
    nb: {
      languageCode: "nb",
      languageName: "Norwegian bokmål",
    },
    nn: {
      languageCode: "nn",
      languageName: "Norwegian nynorsk",
    },
    se: {
      languageCode: "se",
      languageName: "Sami",
    },
  },
  AF: {
    ps: {
      languageCode: "ps",
      languageName: "Pashto, Pushto",
    },
  },
  PL: {
    pl: {
      languageCode: "pl",
      languageName: "Polish",
    },
  },
  PT: {
    pt: {
      languageCode: "pt",
      languageName: "Portuguese",
    },
  },
  PE: {
    qu: {
      languageCode: "qu",
      languageName: "Quechua",
    },
  },
  CH: {
    rm: {
      languageCode: "rm",
      languageName: "Romansh",
    },
  },
  RO: {
    ro: {
      languageCode: "ro",
      languageName: "Romanian",
    },
  },
  WS: {
    sm: {
      languageCode: "sm",
      languageName: "Samoan",
    },
  },
  CF: {
    sg: {
      languageCode: "sg",
      languageName: "Sango",
    },
  },
  RS: {
    sr: {
      languageCode: "sr",
      languageName: "Serbian",
    },
    sh: {
      languageCode: "sh",
      languageName: "Serbo-Croatian",
    },
  },
  LS: {
    st: {
      languageCode: "st",
      languageName: "Sesotho",
    },
  },
  BW: {
    tn: {
      languageCode: "tn",
      languageName: "Setswana",
    },
  },
  PK: {
    sd: {
      languageCode: "sd",
      languageName: "Sindhi",
    },
    ur: {
      languageCode: "ur",
      languageName: "Urdu",
    },
  },
  LK: {
    si: {
      languageCode: "si",
      languageName: "Sinhalese",
    },
  },
  SZ: {
    ss: {
      languageCode: "ss",
      languageName: "Siswati",
    },
  },
  SK: {
    sk: {
      languageCode: "sk",
      languageName: "Slovak",
    },
  },
  SI: {
    sl: {
      languageCode: "sl",
      languageName: "Slovenian",
    },
  },
  SO: {
    so: {
      languageCode: "so",
      languageName: "Somali",
    },
  },
  TZ: {
    sw: {
      languageCode: "sw",
      languageName: "Swahili (Kiswahili)",
    },
  },
  SE: {
    sv: {
      languageCode: "sv",
      languageName: "Swedish",
    },
  },
  PH: {
    tl: {
      languageCode: "tl",
      languageName: "Tagalog",
    },
  },
  PF: {
    ty: {
      languageCode: "ty",
      languageName: "Tahitian",
    },
  },
  TJ: {
    tg: {
      languageCode: "tg",
      languageName: "Tajik",
    },
  },
  TH: {
    th: {
      languageCode: "th",
      languageName: "Thai",
    },
  },
  ER: {
    ti: {
      languageCode: "ti",
      languageName: "Tigrinya",
    },
  },
  TO: {
    to: {
      languageCode: "to",
      languageName: "Tonga",
    },
  },
  TM: {
    tk: {
      languageCode: "tk",
      languageName: "Turkmen",
    },
  },
  UA: {
    uk: {
      languageCode: "uk",
      languageName: "Ukrainian",
    },
  },
  UZ: {
    uz: {
      languageCode: "uz",
      languageName: "Uzbek",
    },
  },
  VN: {
    vi: {
      languageCode: "vi",
      languageName: "Vietnamese",
    },
  },
  "lang-vo": {
    vo: {
      languageCode: "vo",
      languageName: "Volapük",
    },
  },
  BE: {
    wa: {
      languageCode: "wa",
      languageName: "Wallon",
    },
  },
}; // 185 entries

var lns = {};
languages.forEach((l) => {
  const cv =
    l?.mostlyUsedIn?.countryCode ??
    l?.mostlyUsedIn?.countryName ??
    `lang-${l.languageCode}`;

  if (lns[cv])
    lns[cv][l.languageCode] = {
      languageCode: l.languageCode,
      languageName: l.languageName,
    };
  else
    lns[cv] = {
      [l.languageCode]: {
        languageCode: l.languageCode,
        languageName: l.languageName,
      },
    };
});
console.log(lns);

export const countryCodeToNameMapping = {
  AF: "Afghanistan",
  AX: "Åland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "AndorrA",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, The Democratic Republic of the",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Cote D Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and Mcdonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Korea, Democratic People Republic of",
  KR: "Korea, Republic of",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia, The Former Yugoslav Republic of",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States of",
  MD: "Moldova, Republic of",
  MC: "Monaco",
  MN: "Mongolia",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "RWANDA",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  CS: "Serbia and Montenegro",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan, Province of China",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
}; // 241 entries

export const countryNameToCodeMapping = {
  Afghanistan: "AF",
  "Aaland Islands": "AX",
  Albania: "AL",
  Algeria: "DZ",
  "American Samoa": "AS",
  AndorrA: "AD",
  Angola: "AO",
  Anguilla: "AI",
  Antarctica: "AQ",
  "Antigua and Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belgium: "BE",
  Belarus: "BY",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  "Bouvet Island": "BV",
  Brazil: "BR",
  "British Indian Ocean Territory": "IO",
  "Brunei Darussalam": "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  "Christmas Island": "CX",
  "Cocos (Keeling) Islands": "CC",
  Colombia: "CO",
  Comoros: "KM",
  Congo: "CG",
  "Congo, The Democratic Republic of the": "CD",
  "Cook Islands": "CK",
  "Costa Rica": "CR",
  "Cote D Ivoire": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Estonia: "EE",
  Ethiopia: "ET",
  "Falkland Islands (Malvinas)": "FK",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  "French Southern Territories": "TF",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernsey: "GG",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  Haiti: "HT",
  "Heard Island and Mcdonald Islands": "HM",
  "Holy See (Vatican City State)": "VA",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  "Iran, Islamic Republic Of": "IR",
  Iraq: "IQ",
  Ireland: "IE",
  "Isle of Man": "IM",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KI",
  "Korea, Democratic People Republic of": "KP",
  "Korea, Republic of": "KR",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  "Lao People Democratic Republic": "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  "Libyan Arab Jamahiriya": "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macao: "MO",
  "Macedonia, The Former Yugoslav Republic of": "MK",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  "Marshall Islands": "MH",
  Martinique: "MQ",
  Mauritania: "MR",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  "Micronesia, Federated States of": "FM",
  "Moldova, Republic of": "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montserrat: "MS",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "Netherlands Antilles": "AN",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  Niue: "NU",
  "Norfolk Island": "NF",
  "Northern Mariana Islands": "MP",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  "Palestinian Territory, Occupied": "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Pitcairn: "PN",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  Reunion: "RE",
  Romania: "RO",
  "Russian Federation": "RU",
  RWANDA: "RW",
  "Saint Helena": "SH",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Pierre and Miquelon": "PM",
  "Saint Vincent and the Grenadines": "VC",
  Samoa: "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  "Serbia and Montenegro": "CS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  "Solomon Islands": "SB",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Georgia and the South Sandwich Islands": "GS",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Suriname: "SR",
  "Svalbard and Jan Mayen": "SJ",
  Swaziland: "SZ",
  Sweden: "SE",
  Switzerland: "CH",
  "Syrian Arab Republic": "SY",
  "Taiwan, Province of China": "TW",
  Tajikistan: "TJ",
  "Tanzania, United Republic of": "TZ",
  Thailand: "TH",
  "Timor-Leste": "TL",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  "Turks and Caicos Islands": "TC",
  Tuvalu: "TV",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "United States Minor Outlying Islands": "UM",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  Venezuela: "VE",
  "Viet Nam": "VN",
  "British Virgin Islands": "VG",
  "Virgin Islands, U.S.": "VI",
  "Wallis and Futuna": "WF",
  "Western Sahara": "EH",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
}; // 243 entries

const fromWebsite = [
  {
    countryName: "Afghanistan",
    isdCode: "93",
    isoCountryCode: "AF",
    isoCountryCode2: "AFG",
  },
  {
    countryName: "Albania",
    isdCode: "355",
    isoCountryCode: "AL",
    isoCountryCode2: "ALB",
  },
  {
    countryName: "Algeria",
    isdCode: "213",
    isoCountryCode: "DZ",
    isoCountryCode2: "DZA",
  },
  {
    countryName: "American Samoa",
    isdCode: "1-684",
    isoCountryCode: "AS",
    isoCountryCode2: "ASM",
  },
  {
    countryName: "Andorra",
    isdCode: "376",
    isoCountryCode: "AD",
    isoCountryCode2: "AND",
  },
  {
    countryName: "Angola",
    isdCode: "244",
    isoCountryCode: "AO",
    isoCountryCode2: "AGO",
  },
  {
    countryName: "Anguilla",
    isdCode: "1-264",
    isoCountryCode: "AI",
    isoCountryCode2: "AIA",
  },
  {
    countryName: "Antartica",
    isdCode: "672",
    isoCountryCode: "AQ",
    isoCountryCode2: "ATA",
  },
  {
    countryName: "Antigua and Barbuda",
    isdCode: "1-268",
    isoCountryCode: "AG",
    isoCountryCode2: "ATG",
  },
  {
    countryName: "Argentina",
    isdCode: "54",
    isoCountryCode: "AR",
    isoCountryCode2: "ARG",
  },
  {
    countryName: "Armenia",
    isdCode: "374",
    isoCountryCode: "AM",
    isoCountryCode2: "ARM",
  },
  {
    countryName: "Aruba",
    isdCode: "297",
    isoCountryCode: "AW",
    isoCountryCode2: "ABW",
  },
  {
    countryName: "Australia",
    isdCode: "61",
    isoCountryCode: "AU",
    isoCountryCode2: "AUS",
  },
  {
    countryName: "Austria",
    isdCode: "43",
    isoCountryCode: "AT",
    isoCountryCode2: "AUT",
  },
  {
    countryName: "Azerbaijan",
    isdCode: "994",
    isoCountryCode: "AZ",
    isoCountryCode2: "AZE",
  },
  {
    countryName: "Bahamas",
    isdCode: "1-242",
    isoCountryCode: "BS",
    isoCountryCode2: "BHS",
  },
  {
    countryName: "Bahrain",
    isdCode: "973",
    isoCountryCode: "BH",
    isoCountryCode2: "BHR",
  },
  {
    countryName: "Bangladesh",
    isdCode: "880",
    isoCountryCode: "BD",
    isoCountryCode2: "BGD",
  },
  {
    countryName: "Barbados",
    isdCode: "1-246",
    isoCountryCode: "BB",
    isoCountryCode2: "BRB",
  },
  {
    countryName: "Belarus",
    isdCode: "375",
    isoCountryCode: "BY",
    isoCountryCode2: "BLR",
  },
  {
    countryName: "Belgium",
    isdCode: "32",
    isoCountryCode: "BE",
    isoCountryCode2: "BEL",
  },
  {
    countryName: "Belize",
    isdCode: "501",
    isoCountryCode: "BZ",
    isoCountryCode2: "BLZ",
  },
  {
    countryName: "Benin",
    isdCode: "229",
    isoCountryCode: "BJ",
    isoCountryCode2: "BEN",
  },
  {
    countryName: "Bermuda",
    isdCode: "1-441",
    isoCountryCode: "BM",
    isoCountryCode2: "BMU",
  },
  {
    countryName: "Bhutan",
    isdCode: "975",
    isoCountryCode: "BT",
    isoCountryCode2: "BTN",
  },
  {
    countryName: "Bolivia",
    isdCode: "591",
    isoCountryCode: "BO",
    isoCountryCode2: "BOL",
  },
  {
    countryName: "Bosnia and Herzegovina",
    isdCode: "387",
    isoCountryCode: "BA",
    isoCountryCode2: "BIH",
  },
  {
    countryName: "Botswana",
    isdCode: "267",
    isoCountryCode: "BW",
    isoCountryCode2: "BWA",
  },
  {
    countryName: "Brazil",
    isdCode: "55",
    isoCountryCode: "BR",
    isoCountryCode2: "BRA",
  },
  {
    countryName: "British Indian Ocean Territory",
    isdCode: "246",
    isoCountryCode: "IO",
    isoCountryCode2: "IOT",
  },
  {
    countryName: "British Virgin Islands",
    isdCode: "1-284",
    isoCountryCode: "VG",
    isoCountryCode2: "VGB",
  },
  {
    countryName: "Brunei",
    isdCode: "673",
    isoCountryCode: "BN",
    isoCountryCode2: "BRN",
  },
  {
    countryName: "Bulgaria",
    isdCode: "359",
    isoCountryCode: "BG",
    isoCountryCode2: "BGR",
  },
  {
    countryName: "Burkina Faso",
    isdCode: "226",
    isoCountryCode: "BF",
    isoCountryCode2: "BFA",
  },
  {
    countryName: "Burundi",
    isdCode: "257",
    isoCountryCode: "BI",
    isoCountryCode2: "BDI",
  },
  {
    countryName: "Cabo Verde",
    isdCode: "238",
    isoCountryCode: "CV",
    isoCountryCode2: "CPV",
  },
  {
    countryName: "Cambodia",
    isdCode: "855",
    isoCountryCode: "KH",
    isoCountryCode2: "KHM",
  },
  {
    countryName: "Cameroon",
    isdCode: "237",
    isoCountryCode: "CM",
    isoCountryCode2: "CMR",
  },
  {
    countryName: "Canada",
    isdCode: "1",
    isoCountryCode: "CA",
    isoCountryCode2: "CAN",
  },
  {
    countryName: "Cayman Islands",
    isdCode: "1-345",
    isoCountryCode: "KY",
    isoCountryCode2: "CYM",
  },
  {
    countryName: "Central African Republic",
    isdCode: "236",
    isoCountryCode: "CF",
    isoCountryCode2: "CAF",
  },
  {
    countryName: "Chad",
    isdCode: "235",
    isoCountryCode: "TD",
    isoCountryCode2: "TCD",
  },
  {
    countryName: "Chile",
    isdCode: "56",
    isoCountryCode: "CL",
    isoCountryCode2: "CHL",
  },
  {
    countryName: "China",
    isdCode: "86",
    isoCountryCode: "CN",
    isoCountryCode2: "CHN",
  },
  {
    countryName: "Christmas Island",
    isdCode: "61",
    isoCountryCode: "CX",
    isoCountryCode2: "CXR",
  },
  {
    countryName: "Cocos Islands",
    isdCode: "61",
    isoCountryCode: "CC",
    isoCountryCode2: "CCK",
  },
  {
    countryName: "Colombia",
    isdCode: "57",
    isoCountryCode: "CO",
    isoCountryCode2: "COL",
  },
  {
    countryName: "Comoros",
    isdCode: "269",
    isoCountryCode: "KM",
    isoCountryCode2: "COM",
  },
  {
    countryName: "Congo",
    isdCode: "242",
    isoCountryCode: "CG",
    isoCountryCode2: "COG",
  },
  {
    countryName: "Cook Islands",
    isdCode: "682",
    isoCountryCode: "CK",
    isoCountryCode2: "COK",
  },
  {
    countryName: "Costa Rica",
    isdCode: "506",
    isoCountryCode: "CR",
    isoCountryCode2: "CRI",
  },
  {
    countryName: "Croatia",
    isdCode: "385",
    isoCountryCode: "HR",
    isoCountryCode2: "HRV",
  },
  {
    countryName: "Cuba",
    isdCode: "53",
    isoCountryCode: "CU",
    isoCountryCode2: "CUB",
  },
  {
    countryName: "Curaçao",
    isdCode: "599",
    isoCountryCode: "CW",
    isoCountryCode2: "CUW",
  },
  {
    countryName: "Cyprus",
    isdCode: "357",
    isoCountryCode: "CY",
    isoCountryCode2: "CYP",
  },
  {
    countryName: "Czech Republic (Czechia)",
    isdCode: "420",
    isoCountryCode: "CZ",
    isoCountryCode2: "CZE",
  },
  {
    countryName: "Côte d'Ivoire",
    isdCode: "225",
    isoCountryCode: "CI",
    isoCountryCode2: "CIV",
  },
  {
    countryName: "Denmark",
    isdCode: "45",
    isoCountryCode: "DK",
    isoCountryCode2: "DNK",
  },
  {
    countryName: "Djibouti",
    isdCode: "253",
    isoCountryCode: "DJ",
    isoCountryCode2: "DJI",
  },
  {
    countryName: "Dominica",
    isdCode: "1-767",
    isoCountryCode: "DM",
    isoCountryCode2: "DMA",
  },
  {
    countryName: "Dominican Republic",
    isdCode: "1-809, 1-829, 1-849",
    isoCountryCode: "DO",
    isoCountryCode2: "DOM",
  },
  {
    countryName: "DR Congo",
    isdCode: "243",
    isoCountryCode: "CD",
    isoCountryCode2: "COD",
  },
  {
    countryName: "Ecuador",
    isdCode: "593",
    isoCountryCode: "EC",
    isoCountryCode2: "ECU",
  },
  {
    countryName: "Egypt",
    isdCode: "20",
    isoCountryCode: "EG",
    isoCountryCode2: "EGY",
  },
  {
    countryName: "El Salvador",
    isdCode: "503",
    isoCountryCode: "SV",
    isoCountryCode2: "SLV",
  },
  {
    countryName: "Equatorial Guinea",
    isdCode: "240",
    isoCountryCode: "GQ",
    isoCountryCode2: "GNQ",
  },
  {
    countryName: "Eritrea",
    isdCode: "291",
    isoCountryCode: "ER",
    isoCountryCode2: "ERI",
  },
  {
    countryName: "Estonia",
    isdCode: "372",
    isoCountryCode: "EE",
    isoCountryCode2: "EST",
  },
  {
    countryName: "Eswatini",
    isdCode: "268",
    isoCountryCode: "SZ",
    isoCountryCode2: "SWZ",
  },
  {
    countryName: "Ethiopia",
    isdCode: "251",
    isoCountryCode: "ET",
    isoCountryCode2: "ETH",
  },
  {
    countryName: "Faeroe Islands",
    isdCode: "298",
    isoCountryCode: "FO",
    isoCountryCode2: "FRO",
  },
  {
    countryName: "Falkland Islands",
    isdCode: "500",
    isoCountryCode: "FK",
    isoCountryCode2: "FLK",
  },
  {
    countryName: "Fiji",
    isdCode: "679",
    isoCountryCode: "FJ",
    isoCountryCode2: "FJI",
  },
  {
    countryName: "Finland",
    isdCode: "358",
    isoCountryCode: "FI",
    isoCountryCode2: "FIN",
  },
  {
    countryName: "France",
    isdCode: "33",
    isoCountryCode: "FR",
    isoCountryCode2: "FRA",
  },
  {
    countryName: "French Polynesia",
    isdCode: "689",
    isoCountryCode: "PF",
    isoCountryCode2: "PYF",
  },
  {
    countryName: "Gabon",
    isdCode: "241",
    isoCountryCode: "GA",
    isoCountryCode2: "GAB",
  },
  {
    countryName: "Gambia",
    isdCode: "220",
    isoCountryCode: "GM",
    isoCountryCode2: "GMB",
  },
  {
    countryName: "Georgia",
    isdCode: "995",
    isoCountryCode: "GE",
    isoCountryCode2: "GEO",
  },
  {
    countryName: "Germany",
    isdCode: "49",
    isoCountryCode: "DE",
    isoCountryCode2: "DEU",
  },
  {
    countryName: "Ghana",
    isdCode: "233",
    isoCountryCode: "GH",
    isoCountryCode2: "GHA",
  },
  {
    countryName: "Gibraltar",
    isdCode: "350",
    isoCountryCode: "GI",
    isoCountryCode2: "GIB",
  },
  {
    countryName: "Greece",
    isdCode: "30",
    isoCountryCode: "GR",
    isoCountryCode2: "GRC",
  },
  {
    countryName: "Greenland",
    isdCode: "299",
    isoCountryCode: "GL",
    isoCountryCode2: "GRL",
  },
  {
    countryName: "Grenada",
    isdCode: "1-473",
    isoCountryCode: "GD",
    isoCountryCode2: "GRD",
  },
  {
    countryName: "Guam",
    isdCode: "1-671",
    isoCountryCode: "GU",
    isoCountryCode2: "GUM",
  },
  {
    countryName: "Guatemala",
    isdCode: "502",
    isoCountryCode: "GT",
    isoCountryCode2: "GTM",
  },
  {
    countryName: "Guernsey",
    isdCode: "44-1481",
    isoCountryCode: "GG",
    isoCountryCode2: "GGY",
  },
  {
    countryName: "Guinea",
    isdCode: "224",
    isoCountryCode: "GN",
    isoCountryCode2: "GIN",
  },
  {
    countryName: "Guinea-Bissau",
    isdCode: "245",
    isoCountryCode: "GW",
    isoCountryCode2: "GNB",
  },
  {
    countryName: "Guyana",
    isdCode: "592",
    isoCountryCode: "GY",
    isoCountryCode2: "GUY",
  },
  {
    countryName: "Haiti",
    isdCode: "509",
    isoCountryCode: "HT",
    isoCountryCode2: "HTI",
  },
  {
    countryName: "Holy See",
    isdCode: "379",
    isoCountryCode: "VA",
    isoCountryCode2: "VAT",
  },
  {
    countryName: "Honduras",
    isdCode: "504",
    isoCountryCode: "HN",
    isoCountryCode2: "HND",
  },
  {
    countryName: "Hong Kong",
    isdCode: "852",
    isoCountryCode: "HK",
    isoCountryCode2: "HKG",
  },
  {
    countryName: "Hungary",
    isdCode: "36",
    isoCountryCode: "HU",
    isoCountryCode2: "HUN",
  },
  {
    countryName: "Iceland",
    isdCode: "354",
    isoCountryCode: "IS",
    isoCountryCode2: "ISL",
  },
  {
    countryName: "India",
    isdCode: "91",
    isoCountryCode: "IN",
    isoCountryCode2: "IND",
  },
  {
    countryName: "Indonesia",
    isdCode: "62",
    isoCountryCode: "ID",
    isoCountryCode2: "IDN",
  },
  {
    countryName: "Iran",
    isdCode: "98",
    isoCountryCode: "IR",
    isoCountryCode2: "IRN",
  },
  {
    countryName: "Iraq",
    isdCode: "964",
    isoCountryCode: "IQ",
    isoCountryCode2: "IRQ",
  },
  {
    countryName: "Ireland",
    isdCode: "353",
    isoCountryCode: "IE",
    isoCountryCode2: "IRL",
  },
  {
    countryName: "Isle of Man",
    isdCode: "44-1624",
    isoCountryCode: "IM",
    isoCountryCode2: "IMN",
  },
  {
    countryName: "Israel",
    isdCode: "972",
    isoCountryCode: "IL",
    isoCountryCode2: "ISR",
  },
  {
    countryName: "Italy",
    isdCode: "39",
    isoCountryCode: "IT",
    isoCountryCode2: "ITA",
  },
  {
    countryName: "Jamaica",
    isdCode: "1-876",
    isoCountryCode: "JM",
    isoCountryCode2: "JAM",
  },
  {
    countryName: "Japan",
    isdCode: "81",
    isoCountryCode: "JP",
    isoCountryCode2: "JPN",
  },
  {
    countryName: "Jersey",
    isdCode: "44-1534",
    isoCountryCode: "JE",
    isoCountryCode2: "JEY",
  },
  {
    countryName: "Jordan",
    isdCode: "962",
    isoCountryCode: "JO",
    isoCountryCode2: "JOR",
  },
  {
    countryName: "Kazakhstan",
    isdCode: "7",
    isoCountryCode: "KZ",
    isoCountryCode2: "KAZ",
  },
  {
    countryName: "Kenya",
    isdCode: "254",
    isoCountryCode: "KE",
    isoCountryCode2: "KEN",
  },
  {
    countryName: "Kiribati",
    isdCode: "686",
    isoCountryCode: "KI",
    isoCountryCode2: "KIR",
  },
  {
    countryName: "Kuwait",
    isdCode: "965",
    isoCountryCode: "KW",
    isoCountryCode2: "KWT",
  },
  {
    countryName: "Kyrgyzstan",
    isdCode: "996",
    isoCountryCode: "KG",
    isoCountryCode2: "KGZ",
  },
  {
    countryName: "Laos",
    isdCode: "856",
    isoCountryCode: "LA",
    isoCountryCode2: "LAO",
  },
  {
    countryName: "Latvia",
    isdCode: "371",
    isoCountryCode: "LV",
    isoCountryCode2: "LVA",
  },
  {
    countryName: "Lebanon",
    isdCode: "961",
    isoCountryCode: "LB",
    isoCountryCode2: "LBN",
  },
  {
    countryName: "Lesotho",
    isdCode: "266",
    isoCountryCode: "LS",
    isoCountryCode2: "LSO",
  },
  {
    countryName: "Liberia",
    isdCode: "231",
    isoCountryCode: "LR",
    isoCountryCode2: "LBR",
  },
  {
    countryName: "Libya",
    isdCode: "218",
    isoCountryCode: "LY",
    isoCountryCode2: "LBY",
  },
  {
    countryName: "Liechtenstein",
    isdCode: "423",
    isoCountryCode: "LI",
    isoCountryCode2: "LIE",
  },
  {
    countryName: "Lithuania",
    isdCode: "370",
    isoCountryCode: "LT",
    isoCountryCode2: "LTU",
  },
  {
    countryName: "Luxembourg",
    isdCode: "352",
    isoCountryCode: "LU",
    isoCountryCode2: "LUX",
  },
  {
    countryName: "Macao",
    isdCode: "853",
    isoCountryCode: "MO",
    isoCountryCode2: "MAC",
  },
  {
    countryName: "Madagascar",
    isdCode: "261",
    isoCountryCode: "MG",
    isoCountryCode2: "MDG",
  },
  {
    countryName: "Malawi",
    isdCode: "265",
    isoCountryCode: "MW",
    isoCountryCode2: "MWI",
  },
  {
    countryName: "Malaysia",
    isdCode: "60",
    isoCountryCode: "MY",
    isoCountryCode2: "MYS",
  },
  {
    countryName: "Maldives",
    isdCode: "960",
    isoCountryCode: "MV",
    isoCountryCode2: "MDV",
  },
  {
    countryName: "Mali",
    isdCode: "223",
    isoCountryCode: "ML",
    isoCountryCode2: "MLI",
  },
  {
    countryName: "Malta",
    isdCode: "356",
    isoCountryCode: "MT",
    isoCountryCode2: "MLT",
  },
  {
    countryName: "Marshall Islands",
    isdCode: "692",
    isoCountryCode: "MH",
    isoCountryCode2: "MHL",
  },
  {
    countryName: "Mauritania",
    isdCode: "222",
    isoCountryCode: "MR",
    isoCountryCode2: "MRT",
  },
  {
    countryName: "Mauritius",
    isdCode: "230",
    isoCountryCode: "MU",
    isoCountryCode2: "MUS",
  },
  {
    countryName: "Mayotte",
    isdCode: "262",
    isoCountryCode: "YT",
    isoCountryCode2: "MYT",
  },
  {
    countryName: "Mexico",
    isdCode: "52",
    isoCountryCode: "MX",
    isoCountryCode2: "MEX",
  },
  {
    countryName: "Micronesia",
    isdCode: "691",
    isoCountryCode: "FM",
    isoCountryCode2: "FSM",
  },
  {
    countryName: "Moldova",
    isdCode: "373",
    isoCountryCode: "MD",
    isoCountryCode2: "MDA",
  },
  {
    countryName: "Monaco",
    isdCode: "377",
    isoCountryCode: "MC",
    isoCountryCode2: "MCO",
  },
  {
    countryName: "Mongolia",
    isdCode: "976",
    isoCountryCode: "MN",
    isoCountryCode2: "MNG",
  },
  {
    countryName: "Montenegro",
    isdCode: "382",
    isoCountryCode: "ME",
    isoCountryCode2: "MNE",
  },
  {
    countryName: "Montserrat",
    isdCode: "1-664",
    isoCountryCode: "MS",
    isoCountryCode2: "MSR",
  },
  {
    countryName: "Morocco",
    isdCode: "212",
    isoCountryCode: "MA",
    isoCountryCode2: "MAR",
  },
  {
    countryName: "Mozambique",
    isdCode: "258",
    isoCountryCode: "MZ",
    isoCountryCode2: "MOZ",
  },
  {
    countryName: "Myanmar",
    isdCode: "95",
    isoCountryCode: "MM",
    isoCountryCode2: "MMR",
  },
  {
    countryName: "Namibia",
    isdCode: "264",
    isoCountryCode: "NA",
    isoCountryCode2: "NAM",
  },
  {
    countryName: "Nauru",
    isdCode: "674",
    isoCountryCode: "NR",
    isoCountryCode2: "NRU",
  },
  {
    countryName: "Nepal",
    isdCode: "977",
    isoCountryCode: "NP",
    isoCountryCode2: "NPL",
  },
  {
    countryName: "Netherlands",
    isdCode: "31",
    isoCountryCode: "NL",
    isoCountryCode2: "NLD",
  },
  {
    countryName: "New Caledonia",
    isdCode: "687",
    isoCountryCode: "NC",
    isoCountryCode2: "NCL",
  },
  {
    countryName: "New Zealand",
    isdCode: "64",
    isoCountryCode: "NZ",
    isoCountryCode2: "NZL",
  },
  {
    countryName: "Nicaragua",
    isdCode: "505",
    isoCountryCode: "NI",
    isoCountryCode2: "NIC",
  },
  {
    countryName: "Niger",
    isdCode: "227",
    isoCountryCode: "NE",
    isoCountryCode2: "NER",
  },
  {
    countryName: "Nigeria",
    isdCode: "234",
    isoCountryCode: "NG",
    isoCountryCode2: "NGA",
  },
  {
    countryName: "Niue",
    isdCode: "683",
    isoCountryCode: "NU",
    isoCountryCode2: "NIU",
  },
  {
    countryName: "North Korea",
    isdCode: "850",
    isoCountryCode: "KP",
    isoCountryCode2: "PRK",
  },
  {
    countryName: "North Macedonia",
    isdCode: "389",
    isoCountryCode: "MK",
    isoCountryCode2: "MKD",
  },
  {
    countryName: "Northern Mariana Islands",
    isdCode: "1-670",
    isoCountryCode: "MP",
    isoCountryCode2: "MNP",
  },
  {
    countryName: "Norway",
    isdCode: "47",
    isoCountryCode: "NO",
    isoCountryCode2: "NOR",
  },
  {
    countryName: "Oman",
    isdCode: "968",
    isoCountryCode: "OM",
    isoCountryCode2: "OMN",
  },
  {
    countryName: "Pakistan",
    isdCode: "92",
    isoCountryCode: "PK",
    isoCountryCode2: "PAK",
  },
  {
    countryName: "Palau",
    isdCode: "680",
    isoCountryCode: "PW",
    isoCountryCode2: "PLW",
  },
  {
    countryName: "Panama",
    isdCode: "507",
    isoCountryCode: "PA",
    isoCountryCode2: "PAN",
  },
  {
    countryName: "Papua New Guinea",
    isdCode: "675",
    isoCountryCode: "PG",
    isoCountryCode2: "PNG",
  },
  {
    countryName: "Paraguay",
    isdCode: "595",
    isoCountryCode: "PY",
    isoCountryCode2: "PRY",
  },
  {
    countryName: "Peru",
    isdCode: "51",
    isoCountryCode: "PE",
    isoCountryCode2: "PER",
  },
  {
    countryName: "Philippines",
    isdCode: "63",
    isoCountryCode: "PH",
    isoCountryCode2: "PHL",
  },
  {
    countryName: "Pitcairn Islands",
    isdCode: "64",
    isoCountryCode: "PN",
    isoCountryCode2: "PCN",
  },
  {
    countryName: "Poland",
    isdCode: "48",
    isoCountryCode: "PL",
    isoCountryCode2: "POL",
  },
  {
    countryName: "Portugal",
    isdCode: "351",
    isoCountryCode: "PT",
    isoCountryCode2: "PRT",
  },
  {
    countryName: "Puerto Rico",
    isdCode: "1-787, 1-939",
    isoCountryCode: "PR",
    isoCountryCode2: "PRI",
  },
  {
    countryName: "Qatar",
    isdCode: "974",
    isoCountryCode: "QA",
    isoCountryCode2: "QAT",
  },
  {
    countryName: "Romania",
    isdCode: "40",
    isoCountryCode: "RO",
    isoCountryCode2: "ROU",
  },
  {
    countryName: "Russia",
    isdCode: "7",
    isoCountryCode: "RU",
    isoCountryCode2: "RUS",
  },
  {
    countryName: "Rwanda",
    isdCode: "250",
    isoCountryCode: "RW",
    isoCountryCode2: "RWA",
  },
  {
    countryName: "Réunion",
    isdCode: "262",
    isoCountryCode: "RE",
    isoCountryCode2: "REU",
  },
  {
    countryName: "Saint Barthelemy",
    isdCode: "590",
    isoCountryCode: "BL",
    isoCountryCode2: "BLM",
  },
  {
    countryName: "Saint Helena",
    isdCode: "290",
    isoCountryCode: "SH",
    isoCountryCode2: "SHN",
  },
  {
    countryName: "Saint Kitts & Nevis",
    isdCode: "1-869",
    isoCountryCode: "KN",
    isoCountryCode2: "KNA",
  },
  {
    countryName: "Saint Lucia",
    isdCode: "1-758",
    isoCountryCode: "LC",
    isoCountryCode2: "LCA",
  },
  {
    countryName: "Saint Martin",
    isdCode: "590",
    isoCountryCode: "MF",
    isoCountryCode2: "MAF",
  },
  {
    countryName: "Saint Pierre & Miquelon",
    isdCode: "508",
    isoCountryCode: "PM",
    isoCountryCode2: "SPM",
  },
  {
    countryName: "Samoa",
    isdCode: "685",
    isoCountryCode: "WS",
    isoCountryCode2: "WSM",
  },
  {
    countryName: "San Marino",
    isdCode: "378",
    isoCountryCode: "SM",
    isoCountryCode2: "SMR",
  },
  {
    countryName: "Sao Tome & Principe",
    isdCode: "239",
    isoCountryCode: "ST",
    isoCountryCode2: "STP",
  },
  {
    countryName: "Saudi Arabia",
    isdCode: "966",
    isoCountryCode: "SA",
    isoCountryCode2: "SAU",
  },
  {
    countryName: "Senegal",
    isdCode: "221",
    isoCountryCode: "SN",
    isoCountryCode2: "SEN",
  },
  {
    countryName: "Serbia",
    isdCode: "381",
    isoCountryCode: "RS",
    isoCountryCode2: "SRB",
  },
  {
    countryName: "Seychelles",
    isdCode: "248",
    isoCountryCode: "SC",
    isoCountryCode2: "SYC",
  },
  {
    countryName: "Sierra Leone",
    isdCode: "232",
    isoCountryCode: "SL",
    isoCountryCode2: "SLE",
  },
  {
    countryName: "Singapore",
    isdCode: "65",
    isoCountryCode: "SG",
    isoCountryCode2: "SGP",
  },
  {
    countryName: "Sint Maarten",
    isdCode: "1-721",
    isoCountryCode: "SX",
    isoCountryCode2: "SXM",
  },
  {
    countryName: "Slovakia",
    isdCode: "421",
    isoCountryCode: "SK",
    isoCountryCode2: "SVK",
  },
  {
    countryName: "Slovenia",
    isdCode: "386",
    isoCountryCode: "SI",
    isoCountryCode2: "SVN",
  },
  {
    countryName: "Solomon Islands",
    isdCode: "677",
    isoCountryCode: "SB",
    isoCountryCode2: "SLB",
  },
  {
    countryName: "Somalia",
    isdCode: "252",
    isoCountryCode: "SO",
    isoCountryCode2: "SOM",
  },
  {
    countryName: "South Africa",
    isdCode: "27",
    isoCountryCode: "ZA",
    isoCountryCode2: "ZAF",
  },
  {
    countryName: "South Korea",
    isdCode: "82",
    isoCountryCode: "KR",
    isoCountryCode2: "KOR",
  },
  {
    countryName: "South Sudan",
    isdCode: "211",
    isoCountryCode: "SS",
    isoCountryCode2: "SSD",
  },
  {
    countryName: "Spain",
    isdCode: "34",
    isoCountryCode: "ES",
    isoCountryCode2: "ESP",
  },
  {
    countryName: "Sri Lanka",
    isdCode: "94",
    isoCountryCode: "LK",
    isoCountryCode2: "LKA",
  },
  {
    countryName: "St. Vincent & Grenadines",
    isdCode: "1-784",
    isoCountryCode: "VC",
    isoCountryCode2: "VCT",
  },
  {
    countryName: "State of Palestine",
    isdCode: "970",
    isoCountryCode: "PS",
    isoCountryCode2: "PSE",
  },
  {
    countryName: "Sudan",
    isdCode: "249",
    isoCountryCode: "SD",
    isoCountryCode2: "SDN",
  },
  {
    countryName: "Suriname",
    isdCode: "597",
    isoCountryCode: "SR",
    isoCountryCode2: "SUR",
  },
  {
    countryName: "Svalbard and Jan Mayen",
    isdCode: "47",
    isoCountryCode: "SJ",
    isoCountryCode2: "SJM",
  },
  {
    countryName: "Sweden",
    isdCode: "46",
    isoCountryCode: "SE",
    isoCountryCode2: "SWE",
  },
  {
    countryName: "Switzerland",
    isdCode: "41",
    isoCountryCode: "CH",
    isoCountryCode2: "CHE",
  },
  {
    countryName: "Syria",
    isdCode: "963",
    isoCountryCode: "SY",
    isoCountryCode2: "SYR",
  },
  {
    countryName: "Taiwan",
    isdCode: "886",
    isoCountryCode: "TW",
    isoCountryCode2: "TWN",
  },
  {
    countryName: "Tajikistan",
    isdCode: "992",
    isoCountryCode: "TJ",
    isoCountryCode2: "TJK",
  },
  {
    countryName: "Tanzania",
    isdCode: "255",
    isoCountryCode: "TZ",
    isoCountryCode2: "TZA",
  },
  {
    countryName: "Thailand",
    isdCode: "66",
    isoCountryCode: "TH",
    isoCountryCode2: "THA",
  },
  {
    countryName: "Timor-Leste",
    isdCode: "670",
    isoCountryCode: "TL",
    isoCountryCode2: "TLS",
  },
  {
    countryName: "Togo",
    isdCode: "228",
    isoCountryCode: "TG",
    isoCountryCode2: "TGO",
  },
  {
    countryName: "Tokelau",
    isdCode: "690",
    isoCountryCode: "TK",
    isoCountryCode2: "TKL",
  },
  {
    countryName: "Tonga",
    isdCode: "676",
    isoCountryCode: "TO",
    isoCountryCode2: "TON",
  },
  {
    countryName: "Trinidad and Tobago",
    isdCode: "1-868",
    isoCountryCode: "TT",
    isoCountryCode2: "TTO",
  },
  {
    countryName: "Tunisia",
    isdCode: "216",
    isoCountryCode: "TN",
    isoCountryCode2: "TUN",
  },
  {
    countryName: "Turkey",
    isdCode: "90",
    isoCountryCode: "TR",
    isoCountryCode2: "TUR",
  },
  {
    countryName: "Turkmenistan",
    isdCode: "993",
    isoCountryCode: "TM",
    isoCountryCode2: "TKM",
  },
  {
    countryName: "Turks and Caicos",
    isdCode: "1-649",
    isoCountryCode: "TC",
    isoCountryCode2: "TCA",
  },
  {
    countryName: "Tuvalu",
    isdCode: "688",
    isoCountryCode: "TV",
    isoCountryCode2: "TUV",
  },
  {
    countryName: "U.S. Virgin Islands",
    isdCode: "1-340",
    isoCountryCode: "VI",
    isoCountryCode2: "VIR",
  },
  {
    countryName: "Uganda",
    isdCode: "256",
    isoCountryCode: "UG",
    isoCountryCode2: "UGA",
  },
  {
    countryName: "Ukraine",
    isdCode: "380",
    isoCountryCode: "UA",
    isoCountryCode2: "UKR",
  },
  {
    countryName: "United Arab Emirates",
    isdCode: "971",
    isoCountryCode: "AE",
    isoCountryCode2: "ARE",
  },
  {
    countryName: "United Kingdom",
    isdCode: "44",
    isoCountryCode: "GB",
    isoCountryCode2: "GBR",
  },
  {
    countryName: "United States",
    isdCode: "1",
    isoCountryCode: "US",
    isoCountryCode2: "USA",
  },
  {
    countryName: "Uruguay",
    isdCode: "598",
    isoCountryCode: "UY",
    isoCountryCode2: "URY",
  },
  {
    countryName: "Uzbekistan",
    isdCode: "998",
    isoCountryCode: "UZ",
    isoCountryCode2: "UZB",
  },
  {
    countryName: "Vanuatu",
    isdCode: "678",
    isoCountryCode: "VU",
    isoCountryCode2: "VUT",
  },
  {
    countryName: "Venezuela",
    isdCode: "58",
    isoCountryCode: "VE",
    isoCountryCode2: "VEN",
  },
  {
    countryName: "Vietnam",
    isdCode: "84",
    isoCountryCode: "VN",
    isoCountryCode2: "VNM",
  },
  {
    countryName: "Wallis & Futuna",
    isdCode: "681",
    isoCountryCode: "WF",
    isoCountryCode2: "WLF",
  },
  {
    countryName: "Western Sahara",
    isdCode: "212",
    isoCountryCode: "EH",
    isoCountryCode2: "ESH",
  },
  {
    countryName: "Yemen",
    isdCode: "967",
    isoCountryCode: "YE",
    isoCountryCode2: "YEM",
  },
  {
    countryName: "Zambia",
    isdCode: "260",
    isoCountryCode: "ZM",
    isoCountryCode2: "ZMB",
  },
  {
    countryName: "Zimbabwe",
    isdCode: "263",
    isoCountryCode: "ZW",
    isoCountryCode2: "ZWE",
  },
]; // 238 entries

var cl = {};
CountriesIcons.icons.forEach(
  (c) => (cl[c.displayName] = { ...c, id: cctnm[c.displayName] ?? null })
);
