export const FlashCardsData = {
  languageName: "English",
  languageCode: "en",
  categories: [
    {
      heading: "Colors",
      totalCards: 20,
      completedCards: 5,
      description: "Learn the names of different colors.",
    },
    {
      heading: "Shapes",
      totalCards: 15,
      completedCards: 3,
      description: "Identify various shapes.",
    },
    {
      heading: "Numbers",
      totalCards: 50,
      completedCards: 10,
      description: "Master numbers and counting.",
    },
    {
      heading: "Months",
      totalCards: 12,
      completedCards: 4,
      description: "Learn the months of the year.",
    },
    {
      heading: "Time",
      totalCards: 10,
      completedCards: 2,
      description: "Understand how to tell time.",
    },
    {
      heading: "Events",
      totalCards: 8,
      completedCards: 1,
      description: "Common events and occasions.",
    },
    {
      heading: "Animals",
      totalCards: 30,
      completedCards: 7,
      description: "Names of various animals.",
    },
    {
      heading: "Pets",
      totalCards: 10,
      completedCards: 2,
      description: "Common household pets.",
    },
    {
      heading: "Sea Life",
      totalCards: 15,
      completedCards: 3,
      description: "Marine animals and creatures.",
    },
    {
      heading: "Wildlife",
      totalCards: 20,
      completedCards: 5,
      description: "Animals found in the wild.",
    },
    {
      heading: "Insects",
      totalCards: 10,
      completedCards: 2,
      description: "Different types of insects.",
    },
    {
      heading: "Birds",
      totalCards: 15,
      completedCards: 3,
      description: "Various species of birds.",
    },
    {
      heading: "Livestock",
      totalCards: 10,
      completedCards: 2,
      description: "Farm animals and livestock.",
    },
    {
      heading: "Food",
      totalCards: 25,
      completedCards: 6,
      description: "Common food items.",
    },
    {
      heading: "Fruits",
      totalCards: 20,
      completedCards: 5,
      description: "Names of different fruits.",
    },
    {
      heading: "Veggies",
      totalCards: 20,
      completedCards: 5,
      description: "Names of various vegetables.",
    },
    {
      heading: "Dishes",
      totalCards: 15,
      completedCards: 3,
      description: "Popular food dishes.",
    },
    {
      heading: "Drinks",
      totalCards: 10,
      completedCards: 2,
      description: "Common beverages.",
    },
    {
      heading: "Essentials",
      totalCards: 30,
      completedCards: 7,
      description: "Everyday household items.",
    },
    {
      heading: "Sports",
      totalCards: 15,
      completedCards: 3,
      description: "Names of different sports.",
    },
    {
      heading: "Jobs",
      totalCards: 20,
      completedCards: 5,
      description: "Various professions.",
    },
    {
      heading: "Places",
      totalCards: 10,
      completedCards: 2,
      description: "Common places like police, bank, hospital, school.",
    },
    {
      heading: "Vehicles",
      totalCards: 15,
      completedCards: 3,
      description: "Different types of vehicles.",
    },
    {
      heading: "Furniture",
      totalCards: 10,
      completedCards: 2,
      description: "Common household furniture.",
    },
    {
      heading: "Directions",
      totalCards: 10,
      completedCards: 2,
      description: "Terms for giving directions.",
    },
    {
      heading: "Body",
      totalCards: 20,
      completedCards: 5,
      description: "Names of body parts.",
    },
    {
      heading: "Weather",
      totalCards: 10,
      completedCards: 2,
      description: "Weather-related terms.",
    },
    {
      heading: "Helplines",
      totalCards: 5,
      completedCards: 1,
      description: "Important helpline numbers.",
    },
    {
      heading: "Family",
      totalCards: 15,
      completedCards: 3,
      description: "Family relations.",
    },
    {
      heading: "Services",
      totalCards: 10,
      completedCards: 2,
      description: "Utility services like electricity, water, internet.",
    },
    {
      heading: "Hobbies",
      totalCards: 15,
      completedCards: 3,
      description: "Common hobbies like gaming, music, photography.",
    },
  ],
};
